### ISSUE TITLE
login expired issue

### ISSUE THREAD

**Issue by zhangyiant** [zhangyiant/gtja_trade#4]
```
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    stock_processor.process_stock(stock_symbol)
  File "D:\my_stock\gtja_trade\gtja\stockprocessor.py", line 111, in process_stock
    stock_price = self.trade.get_stock_price(stock_symbol)
  File "D:\my_stock\gtja_trade\gtja\Trade.py", line 272, in get_stock_price
    self.select_menu_frame()
  File "D:\my_stock\gtja_trade\gtja\Trade.py", line 256, in select_menu_frame
    self.select_left_frame()
  File "D:\my_stock\gtja_trade\gtja\Trade.py", line 244, in select_left_frame
    self.driver.switch_to.default_content()
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 52, in default_content
    self._driver.execute(Command.SWITCH_TO_FRAME, {'id': None})
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 登录超时过期，请您重新登录！
Message: Unexpected modal dialog (text: 登录超时过期，请您重新登录！)
Stacktrace:
    at fxdriver.modals.closeUnhandledAlert/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:10085)
    at fxdriver.modals.isModalPresent/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:9993)
    at fxdriver.Timer.prototype.runWhenTrue/g (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:631)
    at fxdriver.Timer.prototype.runWhenTrue (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:633)
    at fxdriver.modals.isModalPresent (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:9989)
    at fxdriver.modals.closeUnhandledAlert (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:10074)
    at nsCommandProcessor.prototype.execute (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/command-processor.js:12731)
    at Dispatcher.executeAs/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/driver-component.js:9558)
    at Resource.prototype.handle (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/driver-component.js:9705)
    at Dispatcher.prototype.dispatch (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/driver-component.js:9652)
    at WebDriverServer/<.handle (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/driver-component.js:12517)
    at createHandlerFunc/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
    at ServerHandler.prototype.handleResponse (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
    at Connection.prototype.process (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
    at RequestReader.prototype._handleResponse (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
    at RequestReader.prototype._processBody (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
    at RequestReader.prototype.onInputStreamReady (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/httpd.js:1393)
    at openModalWindow (resource://gre/components/nsPrompter.js:360)
    at ModalPrompter.prototype.openPrompt (resource://gre/components/nsPrompter.js:550)
    at ModalPrompter.prototype.alert (resource://gre/components/nsPrompter.js:602)
    at ObservingAlert.prototype.alert (file:///C:/Users/Wenwen/AppData/Local/Temp/tmpugtyt994/extensions/fxdriver@googlecode.com/components/prompt-service.js:4745)
    at <anonymous> (https://trade.gtja.com/webtrade/trade/webTradeAction.do?method=searchStackDetail:4)
```

Currently, not sure what's the reason.

**Comment by zhangyiant** [comment]
> Traceback (most recent call last):

>   File "main.py", line 85, in <module>
>     stock_processor.keep_alive()
>   File "D:\my_stock\gtja_trade\gtja\stockprocessor.py", line 53, in keep_alive
>     self.trade.get_current_commission_list()
>   File "D:\my_stock\gtja_trade\gtja\Trade.py", line 368, in get_current_commission_list
>     self.select_menu_frame()
>   File "D:\my_stock\gtja_trade\gtja\Trade.py", line 256, in select_menu_frame
>     self.select_left_frame()
>   File "D:\my_stock\gtja_trade\gtja\Trade.py", line 244, in select_left_frame
>     self.driver.switch_to.default_content()
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\switch_to.py", line 52, in default_content
>     self._driver.execute(Command.SWITCH_TO_FRAME, {'id': None})
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 233, in execute
>     self.error_handler.check_response(response)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
>     raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
> selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 登录超时过期，请您重新登录！
> Message: Unexpected modal dialog (text: 登录超时过期，请您重新登录！)
> Stacktrace:
>     at fxdriver.modals.closeUnhandledAlert/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:10085)
>     at fxdriver.modals.isModalPresent/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:9993)
>     at fxdriver.Timer.prototype.runWhenTrue/g (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:631)
>     at fxdriver.Timer.prototype.runWhenTrue (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:633)
>     at fxdriver.modals.isModalPresent (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:9989)
>     at fxdriver.modals.closeUnhandledAlert (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:10074)
>     at nsCommandProcessor.prototype.execute (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/command-processor.js:12731)
>     at Dispatcher.executeAs/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/driver-component.js:9558)
>     at Resource.prototype.handle (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/driver-component.js:9705)
>     at Dispatcher.prototype.dispatch (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/driver-component.js:9652)
>     at WebDriverServer/<.handle (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/driver-component.js:12517)
>     at createHandlerFunc/< (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:2054)
>     at ServerHandler.prototype.handleResponse (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:2387)
>     at Connection.prototype.process (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:1223)
>     at RequestReader.prototype._handleResponse (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:1677)
>     at RequestReader.prototype._processBody (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:1525)
>     at RequestReader.prototype.onInputStreamReady (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/httpd.js:1393)
>     at openModalWindow (resource://gre/components/nsPrompter.js:360)
>     at ModalPrompter.prototype.openPrompt (resource://gre/components/nsPrompter.js:550)
>     at ModalPrompter.prototype.alert (resource://gre/components/nsPrompter.js:602)
>     at ObservingAlert.prototype.alert (file:///C:/Users/Wenwen/AppData/Local/Temp/tmp0klahhgl/extensions/fxdriver@googlecode.com/components/prompt-service.js:4745)
>     at <anonymous> (https://trade.gtja.com/webtrade/trade/webTradeAction.do?method=searchStackDetail:4)

**Comment by zhangyiant** [comment]
>     self.error_handler.check_response(response)
>   File "C:\Python34\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
>     raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
> selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 登录超时过期，请您重新登录！
> Message: Unexpected modal dialog (text: 登录超时过期，请您重新登录！)
